# Generated by Django 4.2.3 on 2023-12-05 18:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hospitalapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Depatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Department', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Pharmacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Doctor1', models.CharField(max_length=255, null=True)),
                ('Patient1', models.CharField(max_length=255, null=True)),
                ('Symptoms', models.CharField(max_length=255, null=True)),
                ('medicine', models.CharField(max_length=255, null=True)),
                ('Patientno', models.CharField(max_length=255, null=True)),
                ('date1', models.DateField()),
                ('time1', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Pharmacy2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Doctor1', models.CharField(max_length=255, null=True)),
                ('Patient1', models.CharField(max_length=255, null=True)),
                ('Symptoms', models.CharField(max_length=255, null=True)),
                ('medicine', models.CharField(max_length=255, null=True)),
                ('Patientno', models.CharField(max_length=255, null=True)),
                ('date1', models.DateField()),
                ('time1', models.TimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='special',
        ),
        migrations.AddField(
            model_name='appointment',
            name='Symptoms',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='patientno',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='token',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='image',
            field=models.ImageField(blank=True, upload_to='image/'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='patient',
            name='image',
            field=models.ImageField(blank=True, upload_to='image/'),
        ),
        migrations.AddField(
            model_name='patient',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='Pharmacy1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Patient1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('mobile', models.IntegerField(null=True)),
                ('address', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50, null=True)),
                ('image', models.ImageField(blank=True, upload_to='image/')),
                ('email', models.EmailField(max_length=254, null=True)),
                ('deparment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hospitalapp.depatment')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientno', models.CharField(max_length=255, null=True)),
                ('date1', models.DateField()),
                ('time1', models.TimeField()),
                ('token', models.CharField(max_length=255, null=True)),
                ('Symptoms', models.CharField(max_length=255, null=True)),
                ('deparment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hospitalapp.depatment')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitalapp.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitalapp.patient')),
            ],
        ),
        migrations.AddField(
            model_name='appointment',
            name='deparment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hospitalapp.depatment'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='deparment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hospitalapp.depatment'),
        ),
    ]
