# Generated by Django 4.2.3 on 2023-12-06 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0002_depatment_pharmacy_pharmacy2_remove_doctor_special_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='patientid',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
