# Generated by Django 4.2.3 on 2023-12-08 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0004_remove_patient_patientid'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='patientno',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
