# Generated by Django 4.2.3 on 2023-12-10 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0007_alter_appointment_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment1',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hospitalapp.doctor'),
        ),
    ]
