# Generated by Django 4.2.3 on 2023-12-10 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0008_alter_appointment1_doctor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointment1',
        ),
    ]
