# Generated by Django 4.2.3 on 2023-12-10 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0011_alter_appointment_patient_alter_appointment1_patient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment1',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='appointment1',
            name='patient',
        ),
        migrations.DeleteModel(
            name='Appointment',
        ),
        migrations.DeleteModel(
            name='Appointment1',
        ),
    ]
