# Generated by Django 4.2.3 on 2023-12-10 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0012_remove_appointment1_doctor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deparment', models.CharField(max_length=255, null=True)),
                ('patientno', models.CharField(max_length=255, null=True)),
                ('date1', models.DateField()),
                ('time1', models.TimeField()),
                ('token', models.CharField(max_length=255, null=True)),
                ('Symptoms', models.CharField(max_length=255, null=True)),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hospitalapp.doctor')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hospitalapp.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deparment', models.CharField(max_length=255, null=True)),
                ('patientno', models.CharField(max_length=255, null=True)),
                ('date1', models.DateField()),
                ('time1', models.TimeField()),
                ('token', models.CharField(max_length=255, null=True)),
                ('Symptoms', models.CharField(max_length=255, null=True)),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hospitalapp.doctor')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hospitalapp.patient')),
            ],
        ),
    ]
