# Generated by Django 4.2.3 on 2023-12-10 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0013_appointment1_appointment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='patient',
            new_name='patient1',
        ),
        migrations.RenameField(
            model_name='appointment1',
            old_name='patient',
            new_name='patient1',
        ),
    ]
