# Generated by Django 4.2.3 on 2023-12-11 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0002_depatment_pharmacy_pharmacy2_and_more'),
        ('hospitalapp', '0014_rename_patient_appointment_patient1_and_more'),
    ]

    operations = [
    ]
